CREATE TABLE [dbo].[Housing] (
    [Id]            INT             IDENTITY (2000000, 1) NOT NULL,
    [DId]           INT             NULL,
    [DName]         VARCHAR (20)    NULL,
    [AId]           INT             NULL,
    [Area]          VARCHAR (20)    NULL,
    [BuildId]       INT             NULL,
    [BuildName]     VARCHAR (150)   NULL,
    [EId]           INT             NOT NULL,
    [EstateName]    VARCHAR (100)   NULL,
    [RoomId]        INT             NULL,
    [RoomNo]        VARCHAR (100)   NULL,
    [TradeType]     INT             NULL,
    [TotalPrice]    NUMERIC (16, 2) NULL,
    [LeasePrice]    NUMERIC (16, 2) NULL,
    [UnitPrice]     NUMERIC (16, 2) NULL,
    [Owner]         VARCHAR (60)    NULL,
    [OwnerTel]      NVARCHAR (100)  NULL,
    [CostPrice]     NUMERIC (16, 2) NULL,
    [PocNo]         VARCHAR (100)   NULL,
    [PocStatus]     VARCHAR (10)    NULL,
    [Redeem]        INT             NULL,
    [UseStatus]     VARCHAR (10)    NULL,
    [PropertyRight] VARCHAR (10)    NULL,
    [Fitment]       VARCHAR (10)    NULL,
    [HouseStyle]    VARCHAR (10)    NULL,
    [Use]           INT             NOT NULL,
    [MergePy]       NVARCHAR (100)  NULL,
    [MarkDate]      DATETIME        NULL,
    [AddDate]       DATETIME        NULL,
    [AddUId]        INT             NULL,
    [AddUser]       VARCHAR (50)    NULL,
    [AddUDept]      VARCHAR (50)    NULL,
    [AddUDeptId]    INT             NULL,
    [MarkUDept]     VARCHAR (50)    NULL,
    [UDDate]        DATETIME        NULL,
    [MarkUId]       INT             NULL,
    [MarkUser]      VARCHAR (50)    NULL,
    [DelFalg]       INT             NULL,
    CONSTRAINT [PK_Housing] PRIMARY KEY CLUSTERED ([Id] ASC)
);

