CREATE TABLE [dbo].[ZLDCEstateLog] (
    [LogFilename]   VARCHAR (255) NULL,
    [LogRow]        INT           NULL,
    [date]          DATETIME      NULL,
    [time]          DATETIME      NULL,
    [cIp]           VARCHAR (255) NULL,
    [csUsername]    VARCHAR (255) NULL,
    [sSitename]     VARCHAR (255) NULL,
    [sComputername] VARCHAR (255) NULL,
    [sIp]           VARCHAR (255) NULL,
    [sPort]         INT           NULL,
    [csMethod]      VARCHAR (255) NULL,
    [csUriStem]     VARCHAR (255) NULL,
    [csUriQuery]    VARCHAR (255) NULL,
    [scStatus]      INT           NULL,
    [scSubstatus]   INT           NULL,
    [scWin32Status] INT           NULL,
    [scBytes]       INT           NULL,
    [csBytes]       INT           NULL,
    [timeTaken]     INT           NULL,
    [csVersion]     VARCHAR (255) NULL,
    [csHost]        VARCHAR (255) NULL,
    [csUserAgent]   VARCHAR (255) NULL,
    [csCookie]      VARCHAR (255) NULL,
    [csReferer]     VARCHAR (255) NULL,
    [sEvent]        VARCHAR (255) NULL,
    [sProcessType]  VARCHAR (255) NULL,
    [sUserTime]     REAL          NULL,
    [sKernelTime]   REAL          NULL,
    [sPageFaults]   INT           NULL,
    [sTotalProcs]   INT           NULL,
    [sActiveProcs]  INT           NULL,
    [sStoppedProcs] INT           NULL
);

